package com.hose.model;
// default package
// Generated 2016-5-8 15:28:37 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * Donkey generated by hbm2java
 */
@Entity
@Table(name = "donkey", catalog = "donkey_db")
public class Donkey implements java.io.Serializable {

	private Integer id;
	private Integer version;
	private int sn;
	private String farmer;
	private String breedaddress;
	private String supplier;
	private String supplyaddress;
	private String dealtime;
	private String supplytime;
	private String breed;
	private String sex;
	private String agewhendeal;
	private String agewhenkill;
	private String feedpattern;
	private String forage;
	private String feedstatus;
	private String healthstatus;
	private String breedstatus;
	private String killdepartment;
	private String killplace;
	private String killtime;
	private String freshkeepmethod;
	private String freshkeeptime;
	private String splitstatus;
	private String processstatus;
	private String qualitystatus;
	private String qc;
	private String qa;
	private String furquality;
	private String reserved;
	private String factorytime;
	private String imagedir;
	private boolean deleteflag;

	public Donkey() {
	}

	public Donkey(int sn, boolean deleteflag) {
		this.sn = sn;
		this.deleteflag = deleteflag;
	}

	public Donkey(int sn, String farmer, String breedaddress, String supplier, String supplyaddress, String dealtime,
			String supplytime, String breed, String sex, String agewhendeal, String agewhenkill, String feedpattern,
			String forage, String feedstatus, String healthstatus, String breedstatus, String killdepartment,
			String killplace, String killtime, String freshkeepmethod, String freshkeeptime, String splitstatus,
			String processstatus, String qualitystatus, String qc, String qa, String furquality, String reserved,
			String factorytime, String imagedir, Integer version, boolean deleteflag) {
		this.sn = sn;
		this.farmer = farmer;
		this.breedaddress = breedaddress;
		this.supplier = supplier;
		this.supplyaddress = supplyaddress;
		this.dealtime = dealtime;
		this.supplytime = supplytime;
		this.breed = breed;
		this.sex = sex;
		this.agewhendeal = agewhendeal;
		this.agewhenkill = agewhenkill;
		this.feedpattern = feedpattern;
		this.forage = forage;
		this.feedstatus = feedstatus;
		this.healthstatus = healthstatus;
		this.breedstatus = breedstatus;
		this.killdepartment = killdepartment;
		this.killplace = killplace;
		this.killtime = killtime;
		this.freshkeepmethod = freshkeepmethod;
		this.freshkeeptime = freshkeeptime;
		this.splitstatus = splitstatus;
		this.processstatus = processstatus;
		this.qualitystatus = qualitystatus;
		this.qc = qc;
		this.qa = qa;
		this.furquality = furquality;
		this.reserved = reserved;
		this.factorytime = factorytime;
		this.imagedir = imagedir;
		this.version = version;
		this.deleteflag = deleteflag;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "sn", nullable = false)
	public int getSn() {
		return this.sn;
	}

	public void setSn(int sn) {
		this.sn = sn;
	}

	@Column(name = "farmer", length = 64)
	public String getFarmer() {
		return this.farmer;
	}

	public void setFarmer(String farmer) {
		this.farmer = farmer;
	}

	@Column(name = "breedaddress", length = 200)
	public String getBreedaddress() {
		return this.breedaddress;
	}

	public void setBreedaddress(String breedaddress) {
		this.breedaddress = breedaddress;
	}

	@Column(name = "supplier", length = 64)
	public String getSupplier() {
		return this.supplier;
	}

	public void setSupplier(String supplier) {
		this.supplier = supplier;
	}

	@Column(name = "supplyaddress", length = 200)
	public String getSupplyaddress() {
		return this.supplyaddress;
	}

	public void setSupplyaddress(String supplyaddress) {
		this.supplyaddress = supplyaddress;
	}

	@Column(name = "dealtime", length = 64)
	public String getDealtime() {
		return this.dealtime;
	}

	public void setDealtime(String dealtime) {
		this.dealtime = dealtime;
	}

	@Column(name = "supplytime", length = 32)
	public String getSupplytime() {
		return this.supplytime;
	}

	public void setSupplytime(String supplytime) {
		this.supplytime = supplytime;
	}

	@Column(name = "breed", length = 64)
	public String getBreed() {
		return this.breed;
	}

	public void setBreed(String breed) {
		this.breed = breed;
	}

	@Column(name = "sex", length = 32)
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	@Column(name = "agewhendeal", length = 32)
	public String getAgewhendeal() {
		return this.agewhendeal;
	}

	public void setAgewhendeal(String agewhendeal) {
		this.agewhendeal = agewhendeal;
	}

	@Column(name = "agewhenkill", length = 32)
	public String getAgewhenkill() {
		return this.agewhenkill;
	}

	public void setAgewhenkill(String agewhenkill) {
		this.agewhenkill = agewhenkill;
	}

	@Column(name = "feedpattern", length = 64)
	public String getFeedpattern() {
		return this.feedpattern;
	}

	public void setFeedpattern(String feedpattern) {
		this.feedpattern = feedpattern;
	}

	@Column(name = "forage", length = 64)
	public String getForage() {
		return this.forage;
	}

	public void setForage(String forage) {
		this.forage = forage;
	}

	@Column(name = "feedstatus", length = 200)
	public String getFeedstatus() {
		return this.feedstatus;
	}

	public void setFeedstatus(String feedstatus) {
		this.feedstatus = feedstatus;
	}

	@Column(name = "healthstatus", length = 200)
	public String getHealthstatus() {
		return this.healthstatus;
	}

	public void setHealthstatus(String healthstatus) {
		this.healthstatus = healthstatus;
	}

	@Column(name = "breedstatus", length = 200)
	public String getBreedstatus() {
		return this.breedstatus;
	}

	public void setBreedstatus(String breedstatus) {
		this.breedstatus = breedstatus;
	}

	@Column(name = "killdepartment", length = 200)
	public String getKilldepartment() {
		return this.killdepartment;
	}

	public void setKilldepartment(String killdepartment) {
		this.killdepartment = killdepartment;
	}

	@Column(name = "killplace", length = 200)
	public String getKillplace() {
		return this.killplace;
	}

	public void setKillplace(String killplace) {
		this.killplace = killplace;
	}

	@Column(name = "killtime", length = 64)
	public String getKilltime() {
		return this.killtime;
	}

	public void setKilltime(String killtime) {
		this.killtime = killtime;
	}

	@Column(name = "freshkeepmethod", length = 10)
	public String getFreshkeepmethod() {
		return this.freshkeepmethod;
	}

	public void setFreshkeepmethod(String freshkeepmethod) {
		this.freshkeepmethod = freshkeepmethod;
	}

	@Column(name = "freshkeeptime", length = 20)
	public String getFreshkeeptime() {
		return this.freshkeeptime;
	}

	public void setFreshkeeptime(String freshkeeptime) {
		this.freshkeeptime = freshkeeptime;
	}

	@Column(name = "splitstatus", length = 200)
	public String getSplitstatus() {
		return this.splitstatus;
	}

	public void setSplitstatus(String splitstatus) {
		this.splitstatus = splitstatus;
	}

	@Column(name = "processstatus", length = 200)
	public String getProcessstatus() {
		return this.processstatus;
	}

	public void setProcessstatus(String processstatus) {
		this.processstatus = processstatus;
	}

	@Column(name = "qualitystatus", length = 200)
	public String getQualitystatus() {
		return this.qualitystatus;
	}

	public void setQualitystatus(String qualitystatus) {
		this.qualitystatus = qualitystatus;
	}

	@Column(name = "QC", length = 30)
	public String getQc() {
		return this.qc;
	}

	public void setQc(String qc) {
		this.qc = qc;
	}

	@Column(name = "QA", length = 30)
	public String getQa() {
		return this.qa;
	}

	public void setQa(String qa) {
		this.qa = qa;
	}

	@Column(name = "furquality", length = 20)
	public String getFurquality() {
		return this.furquality;
	}

	public void setFurquality(String furquality) {
		this.furquality = furquality;
	}

	@Column(name = "reserved", length = 64)
	public String getReserved() {
		return this.reserved;
	}

	public void setReserved(String reserved) {
		this.reserved = reserved;
	}

	@Column(name = "factorytime", length = 64)
	public String getFactorytime() {
		return this.factorytime;
	}

	public void setFactorytime(String factorytime) {
		this.factorytime = factorytime;
	}

	@Column(name = "imagedir", length = 256)
	public String getImagedir() {
		return this.imagedir;
	}

	public void setImagedir(String imagedir) {
		this.imagedir = imagedir;
	}

	@Column(name = "deleteflag", nullable = false)
	public boolean isDeleteflag() {
		return this.deleteflag;
	}

	public void setDeleteflag(boolean deleteflag) {
		this.deleteflag = deleteflag;
	}

}
